### ISSUE TITLE
Keria crashes if delegate inception "dip" specifies list of witnesses

### ISSUE THREAD

**Issue by psteniusubi** [WebOfTrust/keria#124]
My CreateIdentiferArgs for Identifier.create looks like this.

```
    {
      "delpre": "EF-9CK7CROKNNZnA2wwiqoMoJSGuCymykq2GOjuVIFMq",
      "toad": 3,
      "wits": [
        "BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha",
        "BLskRTInXnMxWaGqcpSyMgo0nYbalW99cGZESrz3zapM",
        "BIKKuvBwpmDVA4Ds-EpL5bt9OqPzWPja2LigFYZN2YfX"
      ]
    }
```

When toad and wits are specified then Keria will crash with this stack trace

```
indexing exn said=ECGkSXTQXhg1u1HDGqse0066uJjUxCrEJ2Dw5TVHexZN
Waiting for fully signed witness receipts for 0
Traceback (most recent call last):
  File "/home/uroot/.local/bin/keria", line 33, in <module>
    sys.exit(load_entry_point('keria', 'console_scripts', 'keria')())
  File "/home/uroot/keria/src/keria/app/cli/keria.py", line 31, in main
    raise ex
  File "/home/uroot/keria/src/keria/app/cli/keria.py", line 25, in main
    doers = args.handler(args)
  File "/home/uroot/keria/src/keria/app/cli/commands/start.py", line 20, in <lambda>
    parser.set_defaults(handler=lambda args: launch(args))
  File "/home/uroot/keria/src/keria/app/cli/commands/start.py", line 84, in launch
    runAgent(name=args.name,
  File "/home/uroot/keria/src/keria/app/cli/commands/start.py", line 117, in runAgent
    directing.runController(doers=doers, expire=expire)
  File "/home/uroot/keripy/src/keri/app/directing.py", line 665, in runController
    doist.do(doers=doers)
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 156, in do
    self.recur()  # increments .tyme runs recur context
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 275, in recur
    tock = dog.send(self.tyme)  # yielded tock == 0.0 means re-run asap
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
    self.done = self.recur(tyme=tyme)  # equv of doist.recur
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
    tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
    self.done = self.recur(tyme=tyme)  # equv of doist.recur
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
    tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
    self.done = self.recur(tyme=tyme)  # equv of doist.recur
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
    tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
    self.done = self.recur(tyme=tyme)  # equv of doist.recur
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
    tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
  File "/home/uroot/keripy/src/keri/app/agenting.py", line 221, in witDo
    yield from self.receipt(pre, sn)
  File "/home/uroot/keripy/src/keri/app/agenting.py", line 100, in receipt
    raise kering.ValidationError(f"invalid response {rep.status} from witnesses {wit}")
keri.kering.ValidationError: invalid response 202 from witnesses BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha
```

**Comment by psteniusubi** [comment]
There's now some other regression related to this. Keria now crashes when running signify-ts/examples/integration-scripts/delegation.ts

```
$ ts-node --esm delegation.ts
Client 1 connected. Client AID: EPsx_MVT6Fw5CWwuyuFb_t_fDcRAhm-oMxrwj_0NNdw6 Agent AID:  ENHB5It39hDvbyStHBWIYUlVKFYMow9HwA4ayXPkGORd
Client 2 connected. Client AID: EA9BvNocV7HaRv-pwqqOoFiaapRsJjrfaMPw99tbiK2W Agent AID:  EDDGz7qIKVVta0jZziHSzG6R_O1uHKaVxc3lpCHRMaAP
Delegator's AID: EFWjK20dkXIzGs_rOD8ggMJRmpw6pf0VAsJrpjD98cBT
Client 2 resolving delegator OOBI
OOBI resolved
Delegate's prefix: EN5eqwZ4vRrB8uTyu3sZiW074jQOo4tQpJ2ZhSPF2Bx4
Delegate waiting for approval...
Delegator approved delegation
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async SignifyClient.fetch (file:///home/uroot/signify-ts/src/keri/app/clienting.ts:206:19)
    at async Operations.get (file:///home/uroot/signify-ts/src/keri/app/coring.ts:88:19)
    at async run (file:///home/uroot/signify-ts/examples/integration-scripts/delegation.ts:95:15)
    at async file:///home/uroot/signify-ts/examples/integration-scripts/delegation.ts:7:1 {
  cause: SocketError: other side closed
      at Socket.onSocketEnd (node:internal/deps/undici/undici:9790:26)
      at Socket.emit (node:events:526:35)
      at Socket.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: '127.0.0.1',
      localPort: 34026,
      remoteAddress: undefined,
      remotePort: undefined,
      remoteFamily: undefined,
      timeout: undefined,
      bytesWritten: 1334,
      bytesRead: 833
    }
  }
}
```

Keria crash

```
The Agency is loaded and waiting for requests...
  Agent: ENHB5It39hDvbyStHBWIYUlVKFYMow9HwA4ayXPkGORd   Controller: EPsx_MVT6Fw5CWwuyuFb_t_fDcRAhm-oMxrwj_0NNdw6
  Agent: EDDGz7qIKVVta0jZziHSzG6R_O1uHKaVxc3lpCHRMaAP   Controller: EA9BvNocV7HaRv-pwqqOoFiaapRsJjrfaMPw99tbiK2W
Unable to find sender EDDGz7qIKVVta0jZziHSzG6R_O1uHKaVxc3lpCHRMaAP in kevers for evt = {'v': 'KERI10JSON0002be_', 't': 'exn', 'd': 'EF9iWQYryIxCy0Ecs-iD6OI6kI2PnacmGMR6c-MjHhA4', 'i': 'EDDGz7qIKVVta0jZziHSzG6R_O1uHKaVxc3lpCHRMaAP', 'p': '', 'dt': '2023-11-21T10:04:23.175482+00:00', 'r': '/delegate/request', 'q': {}, 'a': {'delpre': 'EFWjK20dkXIzGs_rOD8ggMJRmpw6pf0VAsJrpjD98cBT', 'aids': []}, 'e': {'evt': {'v': 'KERI10JSON00015f_', 't': 'dip', 'd': 'EN5eqwZ4vRrB8uTyu3sZiW074jQOo4tQpJ2ZhSPF2Bx4', 'i': 'EN5eqwZ4vRrB8uTyu3sZiW074jQOo4tQpJ2ZhSPF2Bx4', 's': '0', 'kt': '1', 'k': ['DGY4Ye6QeCSnkjfz3TpNCDQzr79rDfFgIsJzQ__ZOq5i'], 'nt': '1', 'n': ['EKfmE_tW4OIwCaMSsjyAf0ZN3I_m2vOi5-DznVaNQ-CW'], 'bt': '0', 'b': [], 'c': [], 'a': [], 'di': 'EFWjK20dkXIzGs_rOD8ggMJRmpw6pf0VAsJrpjD98cBT'}, 'd': 'ELb9c0NmoVHK1u7XlhE_5PifpQ15v-_j6n_2HjJwZGAS'}}.
passing it along to the querier!
Traceback (most recent call last):
  File "/home/uroot/.local/bin/keria", line 33, in <module>
    sys.exit(load_entry_point('keria', 'console_scripts', 'keria')())
  File "/home/uroot/keria/src/keria/app/cli/keria.py", line 31, in main
    raise ex
  File "/home/uroot/keria/src/keria/app/cli/keria.py", line 25, in main
    doers = args.handler(args)
  File "/home/uroot/keria/src/keria/app/cli/commands/start.py", line 20, in <lambda>
    parser.set_defaults(handler=lambda args: launch(args))
  File "/home/uroot/keria/src/keria/app/cli/commands/start.py", line 74, in launch
    runAgent(name=args.name,
  File "/home/uroot/keria/src/keria/app/cli/commands/start.py", line 107, in runAgent
    directing.runController(doers=doers, expire=expire)
  File "/home/uroot/keripy/src/keri/app/directing.py", line 665, in runController
    doist.do(doers=doers)
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 156, in do
    self.recur()  # increments .tyme runs recur context
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 275, in recur
    tock = dog.send(self.tyme)  # yielded tock == 0.0 means re-run asap
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
    self.done = self.recur(tyme=tyme)  # equv of doist.recur
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
    tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
    self.done = self.recur(tyme=tyme)  # equv of doist.recur
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
    tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
    self.done = self.recur(tyme=tyme)  # equv of doist.recur
  File "/home/uroot/keria/src/keria/app/agenting.py", line 661, in recur
    return super(Querier, self).recur(tyme, deeds)
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
    tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
  File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
    self.done = self.recur(tyme=tyme)  # equv of doist.recur
  File "/home/uroot/keripy/src/keri/app/querying.py", line 108, in recur
    kever = self.hab.kevers[self.pre]
  File "/home/uroot/keripy/src/keri/db/basing.py", line 67, in __getitem__
    raise ex  # reraise KeyError
  File "/home/uroot/keripy/src/keri/db/basing.py", line 62, in __getitem__
    return super(dbdict, self).__getitem__(k)
KeyError: 'EDDGz7qIKVVta0jZziHSzG6R_O1uHKaVxc3lpCHRMaAP'
```

**Comment by pfeairheller** [comment]
> There's now some other regression related to this. Keria now crashes when running signify-ts/examples/integration-scripts/delegation.ts
> 
> ```
> $ ts-node --esm delegation.ts
> Client 1 connected. Client AID: EPsx_MVT6Fw5CWwuyuFb_t_fDcRAhm-oMxrwj_0NNdw6 Agent AID:  ENHB5It39hDvbyStHBWIYUlVKFYMow9HwA4ayXPkGORd
> Client 2 connected. Client AID: EA9BvNocV7HaRv-pwqqOoFiaapRsJjrfaMPw99tbiK2W Agent AID:  EDDGz7qIKVVta0jZziHSzG6R_O1uHKaVxc3lpCHRMaAP
> Delegator's AID: EFWjK20dkXIzGs_rOD8ggMJRmpw6pf0VAsJrpjD98cBT
> Client 2 resolving delegator OOBI
> OOBI resolved
> Delegate's prefix: EN5eqwZ4vRrB8uTyu3sZiW074jQOo4tQpJ2ZhSPF2Bx4
> Delegate waiting for approval...
> Delegator approved delegation
> TypeError: fetch failed
>     at Object.fetch (node:internal/deps/undici/undici:11576:11)
>     at async SignifyClient.fetch (file:///home/uroot/signify-ts/src/keri/app/clienting.ts:206:19)
>     at async Operations.get (file:///home/uroot/signify-ts/src/keri/app/coring.ts:88:19)
>     at async run (file:///home/uroot/signify-ts/examples/integration-scripts/delegation.ts:95:15)
>     at async file:///home/uroot/signify-ts/examples/integration-scripts/delegation.ts:7:1 {
>   cause: SocketError: other side closed
>       at Socket.onSocketEnd (node:internal/deps/undici/undici:9790:26)
>       at Socket.emit (node:events:526:35)
>       at Socket.emit (node:domain:489:12)
>       at endReadableNT (node:internal/streams/readable:1359:12)
>       at processTicksAndRejections (node:internal/process/task_queues:82:21) {
>     code: 'UND_ERR_SOCKET',
>     socket: {
>       localAddress: '127.0.0.1',
>       localPort: 34026,
>       remoteAddress: undefined,
>       remotePort: undefined,
>       remoteFamily: undefined,
>       timeout: undefined,
>       bytesWritten: 1334,
>       bytesRead: 833
>     }
>   }
> }
> ```
> 
> Keria crash
> 
> ```
> The Agency is loaded and waiting for requests...
>   Agent: ENHB5It39hDvbyStHBWIYUlVKFYMow9HwA4ayXPkGORd   Controller: EPsx_MVT6Fw5CWwuyuFb_t_fDcRAhm-oMxrwj_0NNdw6
>   Agent: EDDGz7qIKVVta0jZziHSzG6R_O1uHKaVxc3lpCHRMaAP   Controller: EA9BvNocV7HaRv-pwqqOoFiaapRsJjrfaMPw99tbiK2W
> Unable to find sender EDDGz7qIKVVta0jZziHSzG6R_O1uHKaVxc3lpCHRMaAP in kevers for evt = {'v': 'KERI10JSON0002be_', 't': 'exn', 'd': 'EF9iWQYryIxCy0Ecs-iD6OI6kI2PnacmGMR6c-MjHhA4', 'i': 'EDDGz7qIKVVta0jZziHSzG6R_O1uHKaVxc3lpCHRMaAP', 'p': '', 'dt': '2023-11-21T10:04:23.175482+00:00', 'r': '/delegate/request', 'q': {}, 'a': {'delpre': 'EFWjK20dkXIzGs_rOD8ggMJRmpw6pf0VAsJrpjD98cBT', 'aids': []}, 'e': {'evt': {'v': 'KERI10JSON00015f_', 't': 'dip', 'd': 'EN5eqwZ4vRrB8uTyu3sZiW074jQOo4tQpJ2ZhSPF2Bx4', 'i': 'EN5eqwZ4vRrB8uTyu3sZiW074jQOo4tQpJ2ZhSPF2Bx4', 's': '0', 'kt': '1', 'k': ['DGY4Ye6QeCSnkjfz3TpNCDQzr79rDfFgIsJzQ__ZOq5i'], 'nt': '1', 'n': ['EKfmE_tW4OIwCaMSsjyAf0ZN3I_m2vOi5-DznVaNQ-CW'], 'bt': '0', 'b': [], 'c': [], 'a': [], 'di': 'EFWjK20dkXIzGs_rOD8ggMJRmpw6pf0VAsJrpjD98cBT'}, 'd': 'ELb9c0NmoVHK1u7XlhE_5PifpQ15v-_j6n_2HjJwZGAS'}}.
> passing it along to the querier!
> Traceback (most recent call last):
>   File "/home/uroot/.local/bin/keria", line 33, in <module>
>     sys.exit(load_entry_point('keria', 'console_scripts', 'keria')())
>   File "/home/uroot/keria/src/keria/app/cli/keria.py", line 31, in main
>     raise ex
>   File "/home/uroot/keria/src/keria/app/cli/keria.py", line 25, in main
>     doers = args.handler(args)
>   File "/home/uroot/keria/src/keria/app/cli/commands/start.py", line 20, in <lambda>
>     parser.set_defaults(handler=lambda args: launch(args))
>   File "/home/uroot/keria/src/keria/app/cli/commands/start.py", line 74, in launch
>     runAgent(name=args.name,
>   File "/home/uroot/keria/src/keria/app/cli/commands/start.py", line 107, in runAgent
>     directing.runController(doers=doers, expire=expire)
>   File "/home/uroot/keripy/src/keri/app/directing.py", line 665, in runController
>     doist.do(doers=doers)
>   File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 156, in do
>     self.recur()  # increments .tyme runs recur context
>   File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 275, in recur
>     tock = dog.send(self.tyme)  # yielded tock == 0.0 means re-run asap
>   File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
>     self.done = self.recur(tyme=tyme)  # equv of doist.recur
>   File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
>     tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
>   File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
>     self.done = self.recur(tyme=tyme)  # equv of doist.recur
>   File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
>     tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
>   File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
>     self.done = self.recur(tyme=tyme)  # equv of doist.recur
>   File "/home/uroot/keria/src/keria/app/agenting.py", line 661, in recur
>     return super(Querier, self).recur(tyme, deeds)
>   File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
>     tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
>   File "/home/uroot/.local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
>     self.done = self.recur(tyme=tyme)  # equv of doist.recur
>   File "/home/uroot/keripy/src/keri/app/querying.py", line 108, in recur
>     kever = self.hab.kevers[self.pre]
>   File "/home/uroot/keripy/src/keri/db/basing.py", line 67, in __getitem__
>     raise ex  # reraise KeyError
>   File "/home/uroot/keripy/src/keri/db/basing.py", line 62, in __getitem__
>     return super(dbdict, self).__getitem__(k)
> KeyError: 'EDDGz7qIKVVta0jZziHSzG6R_O1uHKaVxc3lpCHRMaAP'
> ```

This is not a regression and a completely different and unrelated issue.  Please open a different issue, against KERIpy so we can track it.  I have a PR already to fix this one.
