### ISSUE TITLE
Requesting HTTPS OOBI with HTTP-only KERIA server causes exception 

### ISSUE THREAD

**Issue by iFergal** [WebOfTrust/keria#129]
I have KERIA started normally (HTTP - so different to https://github.com/WebOfTrust/keria/pull/102) and a Traefik load balancer with TLS termination that routes to the container.

If in `backer-oobis.json` I set `keria.curls` to be the public HTTPS endpoint then I get this error when requesting an OOBI via Signify:
```
2023-11-15 21:24:06 [FALCON] [ERROR] GET /identifiers/issuer/oobis?role=agent => Traceback (most recent call last):
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "/keria/src/keria/app/aiding.py", line 653, in on_get
    for url in murl.naball(kering.Schemes.http):
  File "/usr/local/lib/python3.10/site-packages/hio/help/hicting.py", line 192, in naball
    return list(reversed(self.getall(key)))
KeyError: 'http'
```

Will take a look myself too when I have capacity but in case anyone has an idea already! This is on latest development - [56c20c7](https://github.com/WebOfTrust/keria/commit/56c20c779cd1a93bb33fd25271e58ae802618653).

**Comment by iFergal** [comment]
Ah. My mistake @rodolfomiranda - `56c20c7` was set in my deployment but the container wasn't re-build. :facepalm:

It doesn't crash on the latest now! Closing.
