### ISSUE TITLE
Broken change on the KERIA update on Nov 20, 2023

### ISSUE THREAD

**Issue by nkongsuwan** [WebOfTrust/keria#136]
Here is an error message.
```
2023-11-23 13:41:53 [FALCON] [ERROR] POST /boot => Traceback (most recent call last):
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "/Users/nkongsuwan/Workspace/WebOfTrust/keria/src/keria/app/agenting.py", line 765, in on_post
    agent = self.agency.create(caid=caid)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nkongsuwan/Workspace/WebOfTrust/keria/src/keria/app/agenting.py", line 196, in create
    agent = Agent(agentHby, agentRgy, agentHab,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nkongsuwan/Workspace/WebOfTrust/keria/src/keria/app/agenting.py", line 331, in __init__
    protocoling.loadHandlers(hby=self.hby, exc=self.exc, notifier=self.notifier)
TypeError: loadHandlers() missing 1 required positional argument: 'rgy'
```

**Comment by lenkan** [comment]
That argument was removed here: https://github.com/WebOfTrust/keripy/pull/605/files#diff-0912bd4e804593a32046652e439fce8b194a81b80c20cc664dbf0640119ffa1cR317. You need to update the keripy dependency to get it. For example `pip install -r requirements.txt --force-reinstall`, should do the trick.
