### ISSUE TITLE
KERIA Crash when revoking credential from witnessed multisig AID

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/keria#148]
Related to #146 

# Steps to reproduce

1. Create multisig AID "issuer" with witnesses
2. Create single sig AID "holder" with witnesses
3. Create credential from "issuer" to "holder"
4. Revoke credential from "issuer"

# Actual result

Keria process crashes with stack trace:

```
2023-12-13 15:56:31 [FALCON] [ERROR] DELETE /identifiers/multisig/credentials/EKzTnNMh8hH_mR3t0CHNqFGWl4ewRZxQLY8G3th6vLd6 => Traceback (most recent call last):
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "/home/lenkan/code/keria/src/keria/app/credentialing.py", line 669, in on_delete
    op = self.identifierResource.interact(agent, name, body)
  File "/home/lenkan/code/keria/src/keria/app/aiding.py", line 582, in interact
    op = agent.monitor.submit(hab.kever.prefixer.qb64, longrunning.OpTypes.witness,
  File "/home/lenkan/code/keria/src/keria/core/longrunning.py", line 131, in submit
    return self.get(name)
  File "/home/lenkan/code/keria/src/keria/core/longrunning.py", line 137, in get
    operation = self.status(op)
  File "/home/lenkan/code/keria/src/keria/core/longrunning.py", line 176, in status
    dgkey = dbing.dgKey(kever.prefixer.qb64b, bytes(sdig))
TypeError: cannot convert 'NoneType' object to bytes

Traceback (most recent call last):
  File "/home/lenkan/code/keria/.venv/bin/keria", line 33, in <module>
    sys.exit(load_entry_point('keria', 'console_scripts', 'keria')())
  File "/home/lenkan/code/keria/src/keria/app/cli/keria.py", line 31, in main
    raise ex
  File "/home/lenkan/code/keria/src/keria/app/cli/keria.py", line 25, in main
    doers = args.handler(args)
  File "/home/lenkan/code/keria/src/keria/app/cli/commands/start.py", line 20, in <lambda>
    parser.set_defaults(handler=lambda args: launch(args))
  File "/home/lenkan/code/keria/src/keria/app/cli/commands/start.py", line 74, in launch
    runAgent(name=args.name,
  File "/home/lenkan/code/keria/src/keria/app/cli/commands/start.py", line 107, in runAgent
    directing.runController(doers=doers, expire=expire)
  File "/home/lenkan/code/keria/.venv/lib/python3.10/site-packages/keri/app/directing.py", line 665, in runController
    doist.do(doers=doers)
  File "/home/lenkan/code/keria/.venv/lib/python3.10/site-packages/hio/base/doing.py", line 156, in do
    self.recur()  # increments .tyme runs recur context
  File "/home/lenkan/code/keria/.venv/lib/python3.10/site-packages/hio/base/doing.py", line 275, in recur
    tock = dog.send(self.tyme)  # yielded tock == 0.0 means re-run asap
  File "/home/lenkan/code/keria/.venv/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
    self.done = self.recur(tyme=tyme)  # equv of doist.recur
  File "/home/lenkan/code/keria/.venv/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
    tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
  File "/home/lenkan/code/keria/.venv/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
    self.done = self.recur(tyme=tyme)  # equv of doist.recur
  File "/home/lenkan/code/keria/.venv/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
    tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
  File "/home/lenkan/code/keria/.venv/lib/python3.10/site-packages/hio/base/doing.py", line 564, in do
    self.done = yield from self.recur()  # recur context delegated
  File "/home/lenkan/code/keria/src/keria/app/agenting.py", line 441, in recur
    yield from self.receiptor.receipt(serder.pre, serder.sn)
  File "/home/lenkan/code/keria/.venv/lib/python3.10/site-packages/keri/app/agenting.py", line 65, in receipt
    msg = hab.makeOwnEvent(sn=sn)
  File "/home/lenkan/code/keria/.venv/lib/python3.10/site-packages/keri/app/habbing.py", line 2046, in makeOwnEvent
    serder, sigs, couple = self.getOwnEvent(sn=sn,
  File "/home/lenkan/code/keria/.venv/lib/python3.10/site-packages/keri/app/habbing.py", line 2019, in getOwnEvent
    raise kering.MissingEntryError("Missing event for pre={} at sn={}."
keri.kering.MissingEntryError: Missing event for pre=EOL799E8kq2xpxjEN6aPN4xQuv_5JgCukb1C5RN2F34Y at sn=3.
```

# Expected result

No crash, and credential should be revoked. It is of course entirely possible the actual _error_ is on the client side, but then I expect KERIA to do input validation and respond with a HTTP 4xx error instead.

# Notes

Note that I have not been able to get passed the `credentials().revoke()` part of the credential revocation. I then need to do the multisig handshaking as well, but it crashes before I can get to it.

It might also be possible that this happens for single sig issuer as well, I have not tested that yet.

**Comment by lenkan** [comment]
I have created a reproduction script in signify here: https://github.com/WebOfTrust/signify-ts/pull/202

**Comment by pfeairheller** [comment]
Fixed with PR #197
