### ISSUE TITLE
Regression from keripy findAnchoringEvent rename to findAnchoringSealEvent

### ISSUE THREAD

**Issue by psteniusubi** [WebOfTrust/keria#159]
Unit tests are failing after recent changes in keripy where findAnchoringEvent was renamed to findAnchoringSealEvent

```
Error: -22 10:14:53 [FALCON] [ERROR] POST /identifiers/issuer/registries => Traceback (most recent call last):
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "/home/runner/work/keria/keria/src/keria/app/credentialing.py", line 177, in on_post
    op = agent.monitor.submit(hab.kever.prefixer.qb64, longrunning.OpTypes.registry,
  File "/home/runner/work/keria/keria/src/keria/core/longrunning.py", line 132, in submit
    return self.get(name)
  File "/home/runner/work/keria/keria/src/keria/core/longrunning.py", line 138, in get
    operation = self.status(op)
  File "/home/runner/work/keria/keria/src/keria/core/longrunning.py", line 318, in status
    if self.hby.db.findAnchoringEvent(op.oid, anchor=anchor) is not None:
AttributeError: 'Baser' object has no attribute 'findAnchoringEvent'. Did you mean: 'findAnchoringSealEvent'?
```

**Comment by psteniusubi** [comment]
Fixed in https://github.com/WebOfTrust/keria/pull/157
