### ISSUE TITLE
POST /boot failing with error

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/keria#167]
I am getting errors on latest development when trying to boot new agents:

```
keria-1  | 2024-01-12 15:26:31 [FALCON] [ERROR] POST /boot => Traceback (most recent call last):
keria-1  |   File "falcon/app.py", line 365, in falcon.app.App.__call__
keria-1  |   File "/keria/src/keria/app/agenting.py", line 822, in on_post
keria-1  |     agent = self.agency.create(caid=caid)
keria-1  |   File "/keria/src/keria/app/agenting.py", line 203, in create
keria-1  |     agent = Agent(agentHby, agentRgy, agentHab,
keria-1  |   File "/keria/src/keria/app/agenting.py", line 290, in __init__
keria-1  |     self.swain = delegating.Sealer(hby=hby, proxy=agentHab)
keria-1  | AttributeError: module 'keri.app.delegating' has no attribute 'Sealer'
keria-1  |
```

I think this line should be changed:
https://github.com/WebOfTrust/keria/blob/781ea7ad4f47b515c2250a8481f2eb4e65bc8164/src/keria/app/agenting.py#L290

To

```
self.swain = delegating.Boatswain(hby=hby, proxy=agentHab)
```

**Comment by lenkan** [comment]
Caught in dependency chaos. I think I resolved this.
