### ISSUE TITLE
Transient error with using `client.registries().list(name)`

### ISSUE THREAD

**Issue by nkongsuwan** [WebOfTrust/keria#177]
In Signify-TS, using `client.registries().list(name)` sometimes causes a transient error.

The Signify-TS script has the following error messages:
```
    {"title": "500 Internal Server Error"}

      211 |         if (!res.ok) {
      212 |             const error = await res.text();
    > 213 |             throw new Error(error);
          |                   ^
      214 |         }
      215 |         const isSameAgent =
      216 |             this.agent?.pre === res.headers.get('signify-resource');

      at SignifyClient.fetch (../../src/keri/app/clienting.ts:213:19)
      at async Registries.list (../../src/keri/app/credentialing.ts:553:21)
          at async Promise.all (index 1)
      at async Object.run (multisig-vlei-issuance.test.ts:453:52)
```

The KERIA terminal has the following error messages:
```
2024-01-26 16:27:49 [FALCON] [ERROR] GET /identifiers/GEDA/registries => Traceback (most recent call last):
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "/Users/nkongsuwan/Workspace/WebOfTrust/keria/src/keria/app/credentialing.py", line 90, in on_get
    state=asdict(registry.tever.state())
                 ^^^^^^^^^^^^^^
  File "/Users/nkongsuwan/Workspace/WebOfTrust/keripy/src/keri/vdr/credentialing.py", line 198, in tever
    return self.reger.tevers[self.regk]
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/nkongsuwan/Workspace/WebOfTrust/keripy/src/keri/vdr/viring.py", line 48, in __getitem__
    raise ex  # reraise KeyError
    ^^^^^^^^
  File "/Users/nkongsuwan/Workspace/WebOfTrust/keripy/src/keri/vdr/viring.py", line 43, in __getitem__
    return super(rbdict, self).__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'ECk3nPSAslofBPZFvWXHQKSOldJ2cj-g_guGSfcTt_Ek'
```

**Comment by lenkan** [comment]
This looks like the same issue as #147 ?

I think it is consistently reproduced by doing this: https://github.com/WebOfTrust/signify-ts/pull/202#discussion_r1466462814

**Comment by nkongsuwan** [comment]
I see I will close it since it is redundant.
