### ISSUE TITLE
Internal Server Error when trying to query oobi for delegated multisig AID

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/keria#231]
Currently, we are experiencing internal server errors in KERIA for a multisig AID that has been delegated from another multisig AID created in keripy. The error we are experiencing is this:

```
2024-04-17 12:36:22 [FALCON] [ERROR] GET /oobi/<multisig-prefix>/agent/<agent-prefix> => Traceback (most recent call last):
--
File "falcon/app.py", line 365, in falcon.app.App.__call__
File "/keria/src/keria/end/ending.py", line 74, in on_get
msgs = hab.replyToOobi(aid=aid, role=role, eids=eids)
File "/keria/venv/lib/python3.10/site-packages/keri/app/habbing.py", line 2007, in replyToOobi
return self.replyEndRole(cid=aid, role=role, eids=eids)
File "/keria/venv/lib/python3.10/site-packages/keri/app/habbing.py", line 2527, in replyEndRole
msgs.extend(self.loadEndRole(cid=cid, eid=eid, role=erole))
File "/keria/venv/lib/python3.10/site-packages/keri/app/habbing.py", line 1836, in loadEndRole
msgs.extend(eventing.messagize(serder=serder,
File "/keria/venv/lib/python3.10/site-packages/keri/core/eventing.py", line 1426, in messagize
msg = bytearray(serder.raw)  # make copy into new bytearray so can be deleted
AttributeError: 'NoneType' object has no attribute 'raw'
```

The impliciation of this is that no one can resolve the OOBI of our multisig AID.

We have not been able to create a consistent reproduction. There is a related issue in keripy for witnesses: https://github.com/WebOfTrust/keripy/issues/762.

Does anyone have any idea of what could be causing this?

We are using keria version: 0.1.2

**Comment by 2byrds** [comment]
From our KERI dev meeting:
Related to the fix from @rodolfomiranda which was pushed into KERIpy https://github.com/WebOfTrust/keripy/pull/746. The current instance is probably no good, but in the future this issue shouldn't occur. If you receive an additional signature the escrow was causing it to be deleted.
It was merged to main but isn't available in a release. A dev release can be created on request.

**Comment by lenkan** [comment]
@2byrds I am closing this as it has been resolved with a migration script and it will not happen on new AIDs.
